---
title: Virus and Immune Response Model
output:
  html_document:
    theme: null
    highlight: null
    css: ../styles/dsairm.css
    fig_caption: true
    mathjax: default 
    keep_md: false
    includes:
      #in_header: in_header.txt
      before_body: ../styles/dsairm_before_body.txt
      after_body: ../styles/dsairm_after_body.txt 
bibliography: ../media/references.bib
---

##Overview {#shinytab1}
This app allows exploration of a virus infection model that includes several components of the immune response. Read about the model in the "Model" tab. Then do the tasks described in the "What to do" tab.


##The Model {#shinytab2}

###Model Overview
This model consists of several compartments that capture some of the basic dynamics of virus and immune response during an infection. In this model, we track the following entities, by assigning each to a compartment:

* **U** - uninfected cells 
* **I** - infected cells
* **V** - (free) virus
* **F** - innate immune response
* **T** - CD8 T-cells
* **B** - B-cells
* **A** - Antibodies


In addition to specifying the *compartments* of a model, we need to specify the dynamics determining the changes for each compartment. Broadly speaking, there are processes that increase the numbers in a given compartment/stage, and processes that lead to a reduction. Those processes are sometimes called in-flows and out-flows. 

For our system, we specify the following processes/flows: 

1. Uninfected cells are produced at some rate _n_ and naturally die at some rate _dU_.
2. Virus infects cells at rate _b_.
3. Infected cells produce new virus at rate _p_ and die at rate _dI_.
4. Free virus is removed at rate _dV_ or goes on to infect further uninfected cells. 



###Model Diagram
The diagram illustrating this compartmental model is shown in the figure.


```{r BIdiagram,  fig.cap='Flow diagram for a simple virus infection model..',  echo=FALSE}
```


###Model Equations
Implementing this model as a continuous-time, deterministic model leads to the following set of ordinary differential equations. 

$$\dot U = n - dU - bUV$$ 
$$\dot I = bUV - d_I I$$
$$\dot V = pI - d_V V - gb UV$$




##What to do {#shinytab3}

###Task 1: 

###Task 2: 

###Task 3: 





##Further Information {#shinytab4}

### References


