project:
  type: website
  output-dir: docs
website:
  title: "Former DSAIRM website"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



